### PR TITLE
Feature/thumb vid class name

### PR DESCRIPTION
**Pull request by carafizi1**
#### What problem is this solving?

I'm adding a aditional className to a thumbnail when it links to a video, such as following:
image

#### How to test it?

I've linked this feature in a workspace down below directly to a product that has both a video and a image. A video thumbnail should have a aditional thumbVid class on it.

thumbVid

[Workspace](https://carafizi--acctglobal.myvtex.com/luiz/p)

#### Screenshots or example usage:

A simple "play" button added using CSS over the thumbnail so a user knows its links to a video.

image

#### How does this PR make you feel? [:link:](http://giphy.com/)

image

### CODE REVIEW

**Review by icazevedo — CHANGES_REQUESTED** [review]
Code LGTM, but you should add the new CSS Handle to the docs.

**Comment by carafizi1** [comment]
@icazevedo Just updated the docs!

**Review by carafizi1 — COMMENTED** [review]
Just updated the docs!

**Review by icazevedo — APPROVED** [review]
LGTM

**Review by klzns — APPROVED** [review]
Thanks for the pull request. I changed the solution a bit to use a CSS Handle modifier instead of creating a new handle. I think that having both handles `thumbImg` and `thumbVideo` in the same element would be confusing.

**Review by igorbrasileiro — APPROVED** [review]

**Pull request merged**
