### PR TITLE
Fix: add classes to skuSelectorItems

### PR DESCRIPTION
**Pull request by ygorneves10**
#### What problem is this solving?

Add active classes to skuSelectorItems.

#### How should this be manually tested?

https://dev5--kedscl.myvtex.com/kds-zapatilla-triple-canvas-leopardo-wf63032-fhp/p?skuId=4395312

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

https://monosnap.com/direct/JuGE8lHnJjnEa0rbJEzzKOjSbUo2gT

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [ ]  Patch
> * [x]  Minor
> * [ ]  Major
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

### CODE REVIEW

**Comment by ygorneves10** [comment]
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

**Comment by klzns** [comment]
Hey, thank you very much for this. We were fixing the same time as you haha

We published the changes in a slightly different way through this PR https://github.com/vtex-apps/store-components/pull/716

**Comment by ygorneves10** [comment]
> Hey, thank you very much for this. We were fixing the same time as you haha
> 
> We published the changes in a slightly different way through this PR #716

Thanks @klzns , I think this change (#716 ) helps a lot, but it might not completely solve the problem. For example, there is no a vtex class to active item, so how can I define a background-color only for the active item.

My actually problem is: I need to define a background-color to active items, and change the active color, but I can't find a way to do.

Here's a example after the #716 changes.
https://monosnap.com/direct/y6HCu8U5DZbvgtIhWMnaAGIPLHyjkM

Can I create a PR to add vtex active class only? What do you think?

Thank you

**Comment by Klynger** [comment]
Hi @ygorneves10, I see that we don't have a handle for that and I was thinking about doing this, but if you wanna do it's fine by me. But I saw how you did it and I think is better if we instead of using the styles we could use the [css-handles](https://github.com/vtex-apps/css-handles) app (that I'm already using it in this component) [here is an example of how to do it](https://github.com/vtex-apps/stack-layout/commit/07beeb820b30541bd64f1e8258e88aa13d815c0f)

**Pull request closed without merging**
