### PR TITLE
Feat/show label for variation value

### PR DESCRIPTION
**Pull request by rcmuniz1994**
#### What problem is this solving?

I would like to see the label with the variation value. Like this:

Screenshot from 2021-01-12 16-46-34

#### How to test it?

1. Access this workspace.
2. Click on "Iniciar sesión o registrate"
3. Click on "Crear una cuenta"
4. Register yourself on the store
5. Click on "Iniciar sesión o registrate"
6. Click on "Iniciar sesión"
7. Click on "Recibir código de acceso por e-mail"
8. Fill the input with your email.
9. Click on "Enviar"
10. Check your e-mail to get the code.
11. Fill the input with the received code.
12. Click on "Confirmar"
13. Access a product page that the product has more the one sku variation (e.g. [link to a product](https://usic144--unileverb2b.myvtex.com/)).
14. See that the label "caja" is shown with the product quantity.

[https://usic144--unileverb2b.myvtex.com/](https://usic144--unileverb2b.myvtex.com/)

#### Screenshots or example usage:

Before:
Screenshot from 2021-01-12 17-09-29

After:
Screenshot from 2021-01-12 17-10-10

### CODE REVIEW

**Review by icazevedo — CHANGES_REQUESTED** [review]
I'm not being able to create my account, I'm having an error when registering.
Screen Shot 2021-01-14 at 15 22 21

Looking at the code, I think it would be better if you adapted the existing `showVariationsLabels` to accept a string:

- `'none'`, replacing the existing `false` behavior.
- `'container'`, replacing the existing `true` behavior.
- `'item'`, the new behavior you introduced.
- `'containerAndItem'`, both the old and the new behavior.

The `showVariationsLabels` already defaults to `true`, so you can assume it is a `'container'` unless you receive `false`, which means it should be `'none'`.

**Comment by rcmuniz1994** [comment]
Thanks, @icazevedo . But I need that the "container" (as you said) appears to all variations but the prop `showVariationsLabels` shows only the selected one.

I thought that if I set the prop `showValueForVariation` as `"all"` and `showVariationsLabels` as `true` the labels will appear to all variations, but it didn't happen.

**Comment by rcmuniz1994** [comment]
About your registering error, you could try this:
```
Nombre de la empresa: teste
CIF: X12345678
Email: <your email to receive the authentication code>
Teléfono: 999888777
Diréccion: teste
Número: 123
Ciudad: Barcelona
Código Postal: 08010
Persona que recibirá el pedido: icaro
```
Could you please try to fill those fields like this, please? The missing ones are optional, so you could keep them empty. Try this and chat me if it works.

Thanks for help me! :D

**Comment by icazevedo** [comment]
I'm still unable to register with the data you provided.

About the props, what I suggested was for you to adapt the PR so you can incorporate the behavior you developed to the existing `showVariationsLabels` prop. `selected` is indeed a better name than `container`, so it could be like:

- `'none'`, replacing the existing `false` behavior.
- `'selected'`, replacing the existing `true` behavior.
- `'items'`, the new behavior you introduced.
- `'selectedAndItems'`, both the old and the new behavior.

**Comment by rcmuniz1994** [comment]
Thanks, @icazevedo . I think I get it, I'll try this.

(Off topic...You're from Natal. Cool! Me too!)

**Comment by rcmuniz1994** [comment]
@icazevedo I made the adaptation you asked, but a the boolean type on the props to keep the compatibility. So it's like this:

- `true`: to current `true` behavior.
- `false`: to current `false` behavior.
- `values`: to the new behavior.
- `namesAndValues`: to the older and the new behavior.

What do you think?

**Comment by icazevedo** [comment]
@rcmuniz1994 I don't think it is as readable as if it were only strings. It is understandable when we know where to look in the code, but it isn't when users are dealing with it on `blocks.json` and looking at the docs. I can see users mistakenly using `"false"` instead of `false` and achieving an unwanted behavior, for example.

Also, I preferred when you did the logic for this functionality inside `SelectorItem`, not on `Variation`.

**Comment by rcmuniz1994** [comment]
I see...I adjust as you ask, @icazevedo . But I was thinking on the users that already use the component passing a boolean to this props. What do you suggest about this?

**Comment by icazevedo** [comment]
You can type it as a `boolean | {options}` in TS but just so you can know at the code where the person is coming from (old or new behavior). You can add a comment on the code explaining why it could be a boolean (for backward compatibility) and make write some logic to do as I said before:

> The `showVariationsLabels` already defaults to `true`, so you can assume it is a `'container'` unless you receive `false`, which means it should be `'none'`.

Another alternative is to create a new prop with just string options and deprecate the old one. If the new prop is not set (undefined or null), you could use the value of the old prop as a fallback.

**Comment by rcmuniz1994** [comment]
@icazevedo As you asked, I move for inside `SelectorItem`. Could you check it, please?

**Comment by rcmuniz1994** [comment]
Hi, @icazevedo . How are you? I moved for inside `SelectorItem`. Could you check it, please?

**Comment by rcmuniz1994** [comment]
OBS: the lint errors aren't related with my changes. I already ran `yarn lint --fix` on the `react` directory, but they didn't get fixed.

**Comment by icazevedo** [comment]
Hello @rcmuniz1994! I'm sorry for not looking into this earlier.

I have found some changes that still needed to be done and I did it myself (it wasn't much). I wanted to test on your account but the CIF you provided seems to be used already. Can you provide me another available CIF that I can use to test the solution?

As soon as I validate the changes, I'll upload them so you can test yourself.

**Comment by rcmuniz1994** [comment]
Hi, @icazevedo. No worry, it's okay.
Could you try this CIF: B67189290. I think this one works. Chat me if it doesn't? Thanks for the feedback and contribution. XD

**Comment by icazevedo** [comment]
Hey @rcmuniz1994! I've rebased the branch and done some changes to the code.

The main problem with your last approach was that `name` and `namesAndValues` had different behaviors when it comes to the current `true` behavior. The first acted just like it, but the second one didn't, acting instead on the SelectorItem(s). This would be unclear to users thinking that (as suggested by the name) `namesAndValues` combined the behavior of `values` and `name` as if they were selected individually.

I've changed the names to be a little bit more clear and fixed this behavior. `itemValue` has the same behavior of the first prop you introduced a while back, and `variationAndItemValue` combines both the new and old behavior.

About the account you sent, I was able to login but couldn't find a product with more than 1 option on the SKU Selector, maybe because of location restrictions. I've tested this there anyway and it seems to work just fine. I've also tested on other accounts and it looks fine.

I think @rcmuniz1994 won't be able to access these workspaces, but for any VTEXer reviewing this, here you go:
Look to the size picker:

Ensuring it's backwards compatible -> [Unaltered theme (picking default value = "variation"](https://icarovtex4--eriksbikeshop.myvtex.com/ride-manic-snowboard-2021-pr3e23710/p?skuId=8060762)
Ensuring it's backwards compatible -> [Theme with showVariationsLabels = false](https://icarovtex--eriksbikeshop.myvtex.com/ride-manic-snowboard-2021-pr3e23710/p?skuId=8060762)
[Theme with showVariationsLabels = "itemValue"](https://icarovtex3--eriksbikeshop.myvtex.com/ride-manic-snowboard-2021-pr3e23710/p?skuId=8060762)
[Theme with showVariationsLabels = "variationAndItemValue"](https://icarovtex2--eriksbikeshop.myvtex.com/ride-manic-snowboard-2021-pr3e23710/p?skuId=8060762)

**Review by icazevedo — APPROVED** [review]

**Review by victorhmp — APPROVED** [review]

**Comment by rcmuniz1994** [comment]
@icazevedo Thanks! I did make some adjustments on your register, so I think now you can have products with two variations (try this product https://usic144--unileverb2b.myvtex.com/skip-ultimate-triple-poder-detergente-capsulas-maxima-eficacia-24lav/p).

But I'll check this on my workspace too.

**Comment by rcmuniz1994** [comment]
Hi @icazevedo ! It works perfect for a product with two variations:

Screenshot from 2021-02-03 17-28-11

Thanks again for the review and cooperation.

**Comment by rcmuniz1994** [comment]
@icazevedo how many approves do we need to merge this PR?

**Review by igorbrasileiro — APPROVED** [review]
LGTM! 🚀

**Comment by icazevedo** [comment]
I'll deploy it tomorrow morning @rcmuniz1994 :)

**Comment by rcmuniz1994** [comment]
@icazevedo thanks! XD

**Comment by icazevedo** [comment]
@allcontributors add @rcmuniz1994 for code

**Comment by icazevedo** [comment]
I'll publish the app on the #919 PR! Thanks for contributing :)

**Pull request merged**
